-- Data referensi: 38 provinsi Indonesia + kategori awal.
-- Jalankan setelah 0001_schema_awal.sql.

insert into provinces (nama, slug, kode) values
  ('Aceh', 'aceh', '11'),
  ('Sumatera Utara', 'sumatera-utara', '12'),
  ('Sumatera Barat', 'sumatera-barat', '13'),
  ('Riau', 'riau', '14'),
  ('Jambi', 'jambi', '15'),
  ('Sumatera Selatan', 'sumatera-selatan', '16'),
  ('Bengkulu', 'bengkulu', '17'),
  ('Lampung', 'lampung', '18'),
  ('Kepulauan Bangka Belitung', 'kepulauan-bangka-belitung', '19'),
  ('Kepulauan Riau', 'kepulauan-riau', '21'),
  ('DKI Jakarta', 'dki-jakarta', '31'),
  ('Jawa Barat', 'jawa-barat', '32'),
  ('Jawa Tengah', 'jawa-tengah', '33'),
  ('DI Yogyakarta', 'di-yogyakarta', '34'),
  ('Jawa Timur', 'jawa-timur', '35'),
  ('Banten', 'banten', '36'),
  ('Bali', 'bali', '51'),
  ('Nusa Tenggara Barat', 'nusa-tenggara-barat', '52'),
  ('Nusa Tenggara Timur', 'nusa-tenggara-timur', '53'),
  ('Kalimantan Barat', 'kalimantan-barat', '61'),
  ('Kalimantan Tengah', 'kalimantan-tengah', '62'),
  ('Kalimantan Selatan', 'kalimantan-selatan', '63'),
  ('Kalimantan Timur', 'kalimantan-timur', '64'),
  ('Kalimantan Utara', 'kalimantan-utara', '65'),
  ('Sulawesi Utara', 'sulawesi-utara', '71'),
  ('Sulawesi Tengah', 'sulawesi-tengah', '72'),
  ('Sulawesi Selatan', 'sulawesi-selatan', '73'),
  ('Sulawesi Tenggara', 'sulawesi-tenggara', '74'),
  ('Gorontalo', 'gorontalo', '75'),
  ('Sulawesi Barat', 'sulawesi-barat', '76'),
  ('Maluku', 'maluku', '81'),
  ('Maluku Utara', 'maluku-utara', '82'),
  ('Papua', 'papua', '91'),
  ('Papua Barat', 'papua-barat', '92'),
  ('Papua Selatan', 'papua-selatan', '93'),
  ('Papua Tengah', 'papua-tengah', '94'),
  ('Papua Pegunungan', 'papua-pegunungan', '95'),
  ('Papua Barat Daya', 'papua-barat-daya', '96');

insert into categories (nama, slug) values
  ('Kue basah', 'kue-basah'),
  ('Kue kering', 'kue-kering'),
  ('Kue panggang', 'kue-panggang'),
  ('Dodol', 'dodol'),
  ('Gorengan', 'gorengan'),
  ('Minuman', 'minuman');
